version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "8080:80"
    networks:
      - my_network

  pgadmin4:
    build:
      context: .
      dockerfile: Dockerfile_pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: vovik425@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    networks:
      - my_network

  postgres:
    build:
      context: .
      dockerfile: Dockerfile_postgresql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:

