apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: niglocker-prod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql-container
    image: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: root_password
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: password
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: mysql_user
